version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: kong_user
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: KongPassword!
    volumes:
      - C:/temp/postgres:/var/lib/postgresql/data
    networks:
      - kong-network

  kong-migrations:
    image: kong:3.8
    depends_on:
      - postgres
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres
      KONG_PG_PASSWORD: KongPassword!
      KONG_PG_USER: kong_user
      KONG_PG_DATABASE: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8010       # Admin API
    command: kong migrations bootstrap
    networks:
      - kong-network

  # kong:
  #   image: kong:3.8
  #   depends_on:
  #     - postgres
  #   environment:
  #     KONG_DATABASE: postgres
  #     KONG_PG_HOST: postgres
  #     KONG_PG_PASSWORD: KongPassword!
  #     KONG_PG_USER: kong_user
  #     KONG_PG_DATABASE: kong
  #     KONG_PROXY_ACCESS_LOG: /dev/stdout
  #     KONG_ADMIN_ACCESS_LOG: /dev/stdout
  #     KONG_PROXY_ERROR_LOG: /dev/stderr
  #     KONG_ADMIN_ERROR_LOG: /dev/stderr
  #     KONG_ADMIN_LISTEN: 0.0.0.0:8010
  #     KONG_ADMIN_GUI_LISTEN: 0.0.0.0:8002   # Kong Manager
  #   ports:
  #     - "8000:8000"  # Kong Gateway port
  #     - "8443:8443"  # Kong Gateway port SSL
  #     - "8010:8010"  # Kong Admin API
  #     - "8444:8444"  # Kong Admin API SSL
  #     - "8002:8002"  # Kong Manager port
  #   networks:
  #     - kong-network

networks:
  kong-network:
    driver: bridge
